name = "PkgHelpers"
uuid = "a562b63c-6e73-49f2-82ca-bd0905bcffd6"
authors = ["Uwe Fechner <uwe.fechner.msc@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
